#include <stdio.h>
#include <stdlib.h>
#include <stdbool.h>
#include <string.h>
#include <math.h>

// Function Prototypes
void getSafeInput(char* buffer, int size);
void calculate(double num1, char operator, double num2);

int main() {
    char inputBuffer[256];
    char garbage[256]; // Used to catch trailing characters
    double num1, num2;
    char operator;
    bool isRunning = true;

    printf("========================================\n");
    printf("Supported operations: + (add), - (subtract)\n");
    printf("                      * (multiply), / (divide)\n");
    printf("                      ^ (power), %% (modulo)\n");
    printf("Type 'q' or 'quit' at any time to exit.\n");
    printf("========================================\n");

    while (isRunning) {
        printf("\nEnter expression (e.g., 12.5 * 4): ");
        getSafeInput(inputBuffer, sizeof(inputBuffer));

        // Check for empty input
        if (strlen(inputBuffer) == 0) {
            continue;
        }

        // Check for quit commands
        if (strcmp(inputBuffer, "q") == 0 || strcmp(inputBuffer, "quit") == 0 || strcmp(inputBuffer, "Q") == 0) {
            printf("Exiting calculator. Goodbye!\n");
            isRunning = false;
            continue;
        }

        // FIX 1: The "Silent Truncation" Bug
        // We look for a 4th string element. If the user typed "5 + 5 * 2", '* 2' falls into 'garbage'.
        int parsedItems = sscanf(inputBuffer, "%lf %c %lf %255s", &num1, &operator, &num2, garbage);

        if (parsedItems == 3) {
            // FIX 2: The "Infinity Math" Loophole
            // Block direct inputs of "Inf" or "NaN"
            if (!isfinite(num1) || !isfinite(num2)) {
                printf("Error: Infinity or NaN inputs are not supported.\n");
            } else {
                calculate(num1, operator, num2);
            }
        } else if (parsedItems > 3) {
            printf("Error: Too many inputs. Please calculate one operation at a time.\n");
        } else {
            printf("Error: Invalid format. Please use 'Number Operator Number' (e.g., 5 + 5).\n");
        }
    }

    return 0;
}

// --- Function Definitions ---

void getSafeInput(char* buffer, int size) {
    if (fgets(buffer, size, stdin) != NULL) {
        if (strchr(buffer, '\n') == NULL) {
            int c;
            while ((c = getchar()) != '\n' && c != EOF) {}
        }
        buffer[strcspn(buffer, "\r\n")] = '\0';
    } else {
        printf("\n\n[System Error] Input stream disconnected. Shutting down...\n");
        exit(1);
    }
}

void calculate(double num1, char operator, double num2) {
    double result = 0.0;
    bool success = true;

    switch (operator) {
        case '+':
            result = num1 + num2;
            break;
        case '-':
            result = num1 - num2;
            break;
        case '*':
            result = num1 * num2;
            break;
        case '/':
            if (num2 == 0.0) {
                printf("Math Error: Cannot divide by zero.\n");
                success = false;
            } else {
                result = num1 / num2;
            }
            break;
        case '^':
            result = pow(num1, num2);
            break;
        case '%':
            if (num2 == 0.0) {
                printf("Math Error: Cannot modulo by zero.\n");
                success = false;
            } else {
                result = fmod(num1, num2);
            }
            break;
        default:
            printf("Error: Unknown operator '%c'. Use +, -, *, /, ^, or %%\n", operator);
            success = false;
    }

    // Print result only if the core math was valid
    if (success) {
        // FIX 3: The Imaginary Number Glitch
        // Intercept NaN generated by operations like "-4 ^ 0.5"
        if (isnan(result)) {
            printf("Math Error: Result is Not-a-Number (NaN). Check for imaginary/complex roots.\n");
        }
        // Intercept overflows that result in Infinity
        else if (isinf(result)) {
            printf("Math Error: Result represents Infinity (Overflow).\n");
        }
        else {
            // FIX 4: Floating Point Precision Loss
            // Warn the user if they exceed the 53-bit precision limit (approx. 9 quadrillion)
            if (fabs(result) > 9007199254740992.0) {
                printf("Warning: Number is too large. Standard floating-point precision loss may occur.\n");
            }

            if (result == floor(result)) {
                printf(">>> Result: %.0f\n", result);
            } else {
                printf(">>> Result: %.4f\n", result);
            }
        }
    }
}
